[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[routers]
sim_router ansible_host=network_router ansible_user=root ansible_password=admin123 ansible_connection=ssh

[linux_servers]
target_linux ansible_host=linux_server ansible_user=root ansible_password=admin123 ansible_connection=ssh
